//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITIES
    {
        public int Project_ID { get; set; }
        public int Activity_ID { get; set; }
        public Nullable<System.DateTime> Predicted_Start { get; set; }
        public Nullable<System.DateTime> Actual_Start { get; set; }
        public Nullable<System.DateTime> Predicted_Completion { get; set; }
        public Nullable<System.DateTime> Actual_Completion { get; set; }
        public Nullable<decimal> Estimated_Cost { get; set; }
        public Nullable<decimal> Actual_Cost { get; set; }
    }
}
