//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public int Staff_ID { get; set; }
        public string Staff_Name { get; set; }
        public string Staff_Type { get; set; }
        public string Staff_Contact { get; set; }
        public Nullable<int> work_hours_per_week { get; set; }
        public string Contract__permantent { get; set; }
        public Nullable<decimal> salary_per_hour { get; set; }
    }
}
